version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://mongodb:27017/chatter-box
      REDIS_URL: redis://redis:6379
      JWT_SECRET: jwtSecret
    ports:
      - "3000"
    depends_on:
      - mongodb
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1g
          cpus: '0.5'
        reservations:
          cpus: '0.25'
    command: node --max-old-space-size=1024 ./src/index.js
    networks:
      - network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network: